package sysblo.client;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sysblo.entity.CustomerInfoTbl;
import sysblo.entity.CustomerInfoTblExample;

public interface CustomerInfoTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    int countByExample(CustomerInfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerInfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String accountNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    int insert(CustomerInfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    int insertSelective(CustomerInfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    List<CustomerInfoTbl> selectByExample(CustomerInfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    CustomerInfoTbl selectByPrimaryKey(String accountNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerInfoTbl record, @Param("example") CustomerInfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerInfoTbl record, @Param("example") CustomerInfoTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerInfoTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_mybatis.customer_info_tbl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerInfoTbl record);
}