package sysblo.entity;

import java.util.Date;

public class CustomerInfoTbl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_mybatis.customer_info_tbl.account_num
     *
     * @mbggenerated
     */
    private String accountNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_mybatis.customer_info_tbl.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_mybatis.customer_info_tbl.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_mybatis.customer_info_tbl.branch_code
     *
     * @mbggenerated
     */
    private String branchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_mybatis.customer_info_tbl.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_mybatis.customer_info_tbl.latest_update
     *
     * @mbggenerated
     */
    private Date latestUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_mybatis.customer_info_tbl.account_num
     *
     * @return the value of sample_mybatis.customer_info_tbl.account_num
     *
     * @mbggenerated
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_mybatis.customer_info_tbl.account_num
     *
     * @param accountNum the value for sample_mybatis.customer_info_tbl.account_num
     *
     * @mbggenerated
     */
    public void setAccountNum(String accountNum) {
        this.accountNum = accountNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_mybatis.customer_info_tbl.customer_name
     *
     * @return the value of sample_mybatis.customer_info_tbl.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_mybatis.customer_info_tbl.customer_name
     *
     * @param customerName the value for sample_mybatis.customer_info_tbl.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_mybatis.customer_info_tbl.start_date
     *
     * @return the value of sample_mybatis.customer_info_tbl.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_mybatis.customer_info_tbl.start_date
     *
     * @param startDate the value for sample_mybatis.customer_info_tbl.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_mybatis.customer_info_tbl.branch_code
     *
     * @return the value of sample_mybatis.customer_info_tbl.branch_code
     *
     * @mbggenerated
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_mybatis.customer_info_tbl.branch_code
     *
     * @param branchCode the value for sample_mybatis.customer_info_tbl.branch_code
     *
     * @mbggenerated
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_mybatis.customer_info_tbl.memo
     *
     * @return the value of sample_mybatis.customer_info_tbl.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_mybatis.customer_info_tbl.memo
     *
     * @param memo the value for sample_mybatis.customer_info_tbl.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_mybatis.customer_info_tbl.latest_update
     *
     * @return the value of sample_mybatis.customer_info_tbl.latest_update
     *
     * @mbggenerated
     */
    public Date getLatestUpdate() {
        return latestUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_mybatis.customer_info_tbl.latest_update
     *
     * @param latestUpdate the value for sample_mybatis.customer_info_tbl.latest_update
     *
     * @mbggenerated
     */
    public void setLatestUpdate(Date latestUpdate) {
        this.latestUpdate = latestUpdate;
    }
}